### PR TITLE
[WIP] Use stack for 0.3.0 release, generate new tested-with travis script.

### LINKED ISSUE #38: outdated dependencies
There are new versions of the following dependency packages that pangraph-0.2.1 is not compatible with.

- algebraic-graphs-0.3
- fgl-5.7.0.1
- containers-0.6.0.1

Would you support those latest versions?

### PR DESCRIPTION
**Pull request by thisiswhereitype**
WIP to test build
See changelog
 
closes #38

### CODE REVIEW

**Comment by thisiswhereitype** [comment]
Have used switched to stack to generate package bounds.
Added newest ghc and updated minor ghc versions.

**Comment by thisiswhereitype** [comment]
Have settled on a build with a stack LTS and cabal bounds which seem to build for a few recent versions. The commits here don't match Travis so I will wait for it to sort itself.

**Comment by jhrcek** [comment]
Hello @thisiswhereitype 
Is there any progress with this issue? I'd like to try the library, but can't because the dependency bounds on master don't work with ghc-8.6

**Comment by snowleopard** [comment]
@jhrcek Would you like to take the lead on making the master build with newest GHCs? If yes, feel free to send a PR and I'll review it. 

(I think @thisiswhereitype doesn't have much time to keep up with this library at the moment.)

**Comment by jhrcek** [comment]
Hello @snowleopard and @thisiswhereitype Is there something in particular missing in this PR? It seems to me it improves the version bounds in the cabal file and it has ghc-8.6 - compatible travis config generated by haskell-ci. I see the latest build passed in travis, so to me it seems good to merge.

More work could be done on in this regard (like adding support for ghc 8.8) but I'd first like to understand the current status - at least from your point of view - of this PR before I pick this up.

**Comment by snowleopard** [comment]
@jhrcek Agreed, I think we can merge this PR as is, so I've just done this.

**Comment by debug-ito** [comment]
Could you release the new version of pangraph to hackage? The current version on hackage (0.2.1) doesn't include this change.

**Comment by snowleopard** [comment]
@debug-ito I don't have Hackage upload rights and @thisiswhereitype doesn't seem to be actively maintaining this package right now.

I think we need to add another maintainer to this project. Are you interested in becoming one? You seem to be using Pangraph, and so I hope you'll be able to find some time keep it in good shape.

**Comment by debug-ito** [comment]
Thanks for the quick reply!

I understand the difficult situation. However, I cannot assure the quality of `pangraph` package, so I cannot be a maintainer.

I once used `pangraph` to format graph data model of [net-spider](http://hackage.haskell.org/package/net-spider) into GraphML (the [net-spider-pangraph](http://hackage.haskell.org/package/net-spider-pangraph) package). However, because of #41, I have implemented a GraphML formatter myself. Now personally I don't use net-spider-pangraph.

If pangraph is not updating anymore, I can abandon net-spider-pangraph, too. It's kinda sad, but no problem in practice for me.

**Comment by snowleopard** [comment]
@debug-ito Thanks, I see. In case you change your mind, don't hesitate to get in touch :) 

(I helped design this library, so I could in principle also become a maintainer, but it's always best if the maintainer is also a user of the library, and I'm currently not.)

**Pull request merged**
