### PR TITLE
Add gml support to pangraph

### PR DESCRIPTION
**Pull request by zouroboros**
see #29

### CODE REVIEW

**Comment by snowleopard** [comment]
Many thanks for the PR, I'll review in a few days (currently travelling).

One quick question: is the dependency on `html-entities` essential? It also pulls `unordered-containers` with it. It's not immediately obvious why GML parsing would depend on an HTML library.

**Comment by zouroboros** [comment]
Originally gml was designed to be completely encoded in ASCII and use [HTML entities](https://en.wikipedia.org/wiki/Character_encodings_in_HTML#Character_references) to encode special characters (See also this [spec](http://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf) in the syntax section). Since currently we assume the content of the bytestring to be UTF8 encoded this not needed for special characters except to encode the double quote inside of strings (double quotes are also used to delimit strings in gml).

With some effort we could probably implement this ourselves, if the dependencies are a problem.

**Comment by thisiswhereitype** [comment]
Thanks for your PR. I have a question in the meantime.
Could you add a sample file the `Examples` dir, which can be used in the examples?

**Review by snowleopard — COMMENTED** [review]
In general this all looks good to me, thank you. One small issue is Haddock comments: my understanding is that they will likely not render well, because you typically have a first line comment not ending with a dot, so it will be merged with the next sentence. Could you fix that?

**Comment by snowleopard** [comment]
@zouroboros Thanks for clarifying. If HTML entities are part of GML spec, it seems logical to depend on the corresponding Haskell library.

**Comment by zouroboros** [comment]
I went through the comments and append a dot at the end of every sentence. The haddock output didn't seemed to change though.

**Comment by snowleopard** [comment]
@zouroboros Thank you! It's strange though that Haddock output didn't change -- I expected the dots to now separate previously merged sentences, but perhaps Haddock inserts dots automatically?

Anyway, I'm happy to merge. 

@thisiswhereitype Do you have any further comments?

**Comment by thisiswhereitype** [comment]
I am happy for a merge.

**Pull request merged**
